// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class ElementType
{
    public int ElementId { get; set; }

    public string ElementName { get; set; }

    public virtual ICollection<FengShuiScore> FengShuiScores { get; set; } = new List<FengShuiScore>();

    public virtual ICollection<KoiFish> KoiFishes { get; set; } = new List<KoiFish>();

    public virtual ICollection<PondFeature> PondFeatures { get; set; } = new List<PondFeature>();

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();
}