// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class FengShuiScore
{
    public int ScoreId { get; set; }

    public int? UserId { get; set; }

    public int? ElementId { get; set; }

    public int? KoiFishId { get; set; }

    public int? PondFeatureId { get; set; }

    public decimal? CompatibilityScore { get; set; }

    public virtual ElementType Element { get; set; }

    public virtual KoiFish KoiFish { get; set; }

    public virtual PondFeature PondFeature { get; set; }

    public virtual User User { get; set; }
}