// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class KoiFish
{
    public int KoiFishId { get; set; }

    public string FishName { get; set; }

    public string Description { get; set; }

    public string ImageUrl { get; set; }

    public int? SuitableElementId { get; set; }

    public virtual ICollection<FengShuiScore> FengShuiScores { get; set; } = new List<FengShuiScore>();

    public virtual ElementType SuitableElement { get; set; }
}