// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class PondFeature
{
    public int PondFeatureId { get; set; }

    public string FeatureType { get; set; }

    public string FeatureValue { get; set; }

    public int? SuitableElementId { get; set; }

    public virtual ICollection<FengShuiScore> FengShuiScores { get; set; } = new List<FengShuiScore>();

    public virtual ElementType SuitableElement { get; set; }
}