// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class PostPackage
{
    public int PackageId { get; set; }

    public string PackageName { get; set; }

    public decimal Price { get; set; }

    public int DurationDays { get; set; }

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();
}