// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Statistic
{
    public int StatId { get; set; }

    public DateOnly DateRecorded { get; set; }

    public int? TotalUsers { get; set; }

    public int? TotalPosts { get; set; }

    public int? ActiveUsers { get; set; }

    public int? ActivePosts { get; set; }
}